"""
SnapTrade Sync
=====================
Pulls your Fidelity trade history straight from SnapTrade (a service
that connects to your brokerage on your behalf) instead of you having
to manually export and upload a CSV every time. See:
  - pages/0_Import_Trades.py for the one-time "Register" and "Connect
    Fidelity" steps, and the "Sync Now" button.
  - snaptrade_daily_sync.py for the automatic version of that same
    sync, run once a day after market close.

HOW THE CONNECTION WORKS: you connect your Fidelity account ONCE,
through SnapTrade's own "Connection Portal" - a webpage hosted by
SnapTrade, not this app. You log into Fidelity directly on Fidelity's
own site from there, so your Fidelity password never passes through
SnapTrade or this app at all - only a read-only access token does
(see get_connection_portal_url() below for why it's read-only).

WHERE CREDENTIALS LIVE, IN TWO STAGES:
  1. SNAPTRADE_CLIENT_ID / SNAPTRADE_CONSUMER_KEY (in st.secrets, same
     gitignored-secrets pattern as DATABASE_URL - see database.py)
     identify THIS APP to SnapTrade.
  2. SNAPTRADE_USER_SECRET - generated by register_user() below, the
     FIRST time it's run (see the "Register with SnapTrade" button on
     the Import Trades page). SnapTrade's docs describe a "Personal"
     API key as needing no separate registered user at all - in
     practice, this account still required one, so this project just
     always goes through register_user() and stores what it returns.
     It's as sensitive as a password (it's what proves every later API
     call is really you) and, like a password, SnapTrade only shows it
     back once at creation time - hence needing to save it immediately.
"""

import os
import time
from datetime import datetime

import streamlit as st
from snaptrade_client import SnapTrade

import timeutil

# A fixed identifier for you as a SnapTrade user - NOT sensitive (it's
# an ID, not a secret, like a username rather than a password), so
# it's just a constant here instead of one more thing to store in
# secrets. Whatever value this is doesn't matter as long as it never
# changes once you've registered (see register_user()).
USER_ID = "primary"

# SnapTrade's security "type.code" values that aren't a real stock (or
# stock-like, exchange-traded) position - see fetch_activities()'s
# filter below. Deliberately a denylist, not an allowlist: an unknown
# or missing type is let through rather than silently dropped, since
# being overly permissive here just means an odd row shows up (easy to
# notice), while being overly restrictive would silently hide a real
# trade. "oef" (open-ended mutual fund) is what a Fidelity cash-sweep
# fund like SPAXX is categorized as - that's the one this project
# actually hit in practice; the rest are excluded on the same
# reasoning (not something you'd hold as a tracked stock position).
_NON_STOCK_SECURITY_TYPES = {"oef", "bnd", "crypto", "pm", "struct", "rt", "ut", "wi", "wt"}


def _get_secret_optional(key):
    """
    Same st.secrets-then-env-var lookup as _get_secret() below, but
    returns None instead of raising when nothing's set - used for
    SNAPTRADE_USER_SECRET, which legitimately doesn't exist yet until
    register_user() has been run once, and for the plain "is this
    configured at all" checks the Import Trades page uses to decide
    which step to show.
    """
    try:
        value = st.secrets[key]
        if value:
            return value
    except Exception:
        pass
    return os.environ.get(key) or None


def _get_secret(key):
    """
    Same fallback pattern as database.py's _get_database_url(): reads
    st.secrets first (how the deployed app, and any `streamlit run`
    command, reads .streamlit/secrets.toml), then a plain environment
    variable (how snaptrade_daily_sync.py's GitHub Actions job reads
    it - there's no secrets.toml file in that environment, just a
    repository secret set as an env var). Raises if truly nothing's
    set anywhere.
    """
    value = _get_secret_optional(key)
    if value:
        return value

    raise RuntimeError(
        f"No {key} found. Copy .streamlit/secrets.toml.example to "
        ".streamlit/secrets.toml and fill in your SnapTrade Personal "
        f"API key (or set a {key} environment variable)."
    )


def is_configured():
    """Whether SNAPTRADE_CLIENT_ID/SNAPTRADE_CONSUMER_KEY are set at all - the prerequisite for everything else here."""
    return bool(_get_secret_optional("SNAPTRADE_CLIENT_ID")) and bool(_get_secret_optional("SNAPTRADE_CONSUMER_KEY"))


def is_registered():
    """Whether register_user() has already been run and its result saved as SNAPTRADE_USER_SECRET."""
    return bool(_get_secret_optional("SNAPTRADE_USER_SECRET"))


def _get_client():
    """
    Builds the SnapTrade API client from your secrets.

    `timestamp` (the current time, as a string) is required here even
    though it looks optional in the SDK's own signature - the
    underlying Configuration object only attaches the "timestamp"
    query parameter to a request AT ALL if this was supplied when the
    client was built (see snaptrade_client/configuration.py's
    auth_settings()); leaving it out doesn't raise an error, it just
    silently sends every request without it. That went unnoticed for a
    while because SnapTrade's server was apparently lenient about a
    missing timestamp - until it started rejecting requests outright
    with a bare "Authentication credentials were not provided" 401,
    despite nothing changing on this app's end. A fresh timestamp is
    generated every time this function runs (every API call rebuilds
    its own client - see every other function below), which is exactly
    what a timestamp-based check is meant to have anyway.
    """
    return SnapTrade(
        client_id=_get_secret("SNAPTRADE_CLIENT_ID"),
        consumer_key=_get_secret("SNAPTRADE_CONSUMER_KEY"),
        timestamp=str(int(time.time())),
    )


def _user_credentials():
    """
    Returns (user_id, user_secret) for every user-scoped API call
    below. Raises a plain message if register_user() hasn't been run
    yet - the Import Trades page checks is_registered() itself first
    so this should only ever fire if something calls in out of order.
    """
    user_secret = _get_secret_optional("SNAPTRADE_USER_SECRET")
    if not user_secret:
        raise RuntimeError(
            "SnapTrade user isn't registered yet - use the 'Register with "
            "SnapTrade' button on the Import Trades page first, then save "
            "the secret it gives you as SNAPTRADE_USER_SECRET."
        )
    return USER_ID, user_secret


def register_user():
    """
    One-time step, run once ever: creates your SnapTrade user (see
    docs.snaptrade.com/docs/terminology) and returns the userSecret
    SnapTrade generates for it. Save the return value immediately as
    SNAPTRADE_USER_SECRET (alongside SNAPTRADE_CLIENT_ID/
    SNAPTRADE_CONSUMER_KEY - see .streamlit/secrets.toml.example) -
    SnapTrade only returns it this once, the same way a password is
    normally only shown at creation time.
    """
    client = _get_client()
    response = client.authentication.register_snap_trade_user(user_id=USER_ID)
    return response.body["userSecret"]


def _find_broker_slug(name_contains):
    """
    Looks up a brokerage's SnapTrade "slug" (the short code the
    Connection Portal expects, e.g. for Fidelity) by matching against
    its display name - rather than hardcoding a guessed slug string
    here, which could quietly be wrong. Returns None (falls back to
    the portal's own brokerage picker) if nothing matches.
    """
    client = _get_client()
    response = client.reference_data.list_all_brokerages()
    for brokerage in response.body:
        display_name = (brokerage.get("display_name") or brokerage.get("name") or "")
        if name_contains.lower() in display_name.lower():
            return brokerage.get("slug")
    return None


def get_connection_portal_url(broker="Fidelity", reconnect=None):
    """
    Returns a one-time link to SnapTrade's Connection Portal - open it
    in a browser to connect (or, if `reconnect` is a connection ID,
    reconnect) a brokerage account.

    Read-only on purpose (connection_type="read"): this app only ever
    reads trade history, it never places trades, so there's no reason
    to grant more access than that. A read-only connection means that
    even in a worst case - SnapTrade compromised, or this app's own
    API key leaked - whatever's exposed can't be used to move money or
    place orders.

    `broker` is looked up by name via _find_broker_slug() so the
    portal jumps straight to Fidelity's login step instead of showing
    the full brokerage picker; pass None to always show the picker.
    """
    user_id, user_secret = _user_credentials()
    slug = _find_broker_slug(broker) if broker else None
    client = _get_client()
    response = client.authentication.login_snap_trade_user(
        user_id=user_id, user_secret=user_secret,
        broker=slug, connection_type="read", reconnect=reconnect,
    )
    return response.body["redirectURI"]


def list_connected_accounts():
    """
    Returns every brokerage account currently connected - each a dict
    with at least "id", "name", and "institution_name". Used to find
    the account_id(s) fetch_activities() needs, and to show what's
    already connected on the Import Trades page.
    """
    user_id, user_secret = _user_credentials()
    client = _get_client()
    response = client.account_information.list_user_accounts(user_id=user_id, user_secret=user_secret)
    return list(response.body)


def fetch_activities(start_date, end_date):
    """
    Pulls every BUY/SELL activity across all connected accounts
    between start_date and end_date (inclusive, both plain `date`
    objects), already normalized into the exact same shape
    analyze_trades.py's load_transactions()/load_transactions_schwab()
    produce:
        {"date": datetime, "symbol": "AAPL", "action": "BUY",
         "price": 150.0, "quantity": 100}
    so the result can go straight into database.py's shared insert
    helper alongside CSV-imported rows, with the exact same
    duplicate-safe behavior (see database._insert_transactions()).

    Option activity is skipped (option_symbol is only set on an option
    trade) - this project tracks stocks only, the same exclusion the
    CSV importers already apply for symbols starting with "-". Cash
    sweep / money-market fund activity is skipped too (see
    _NON_STOCK_SECURITY_TYPES below) - Fidelity automatically moves
    cash in and out of a settlement fund (e.g. "SPAXX") constantly, and
    SnapTrade reports every one of those sweeps as its own BUY/SELL,
    which isn't a real trade or position at all.

    Note: SnapTrade's transaction data is cached and refreshed once a
    day, about a day behind - a trade made today typically won't show
    up here until tomorrow, same as the old manual CSV-export
    workflow already was.
    """
    user_id, user_secret = _user_credentials()
    client = _get_client()
    transactions = []

    for account in list_connected_accounts():
        offset = 0
        while True:
            response = client.account_information.get_account_activities(
                account_id=account["id"], user_id=user_id, user_secret=user_secret,
                start_date=start_date, end_date=end_date,
                type="BUY,SELL", offset=offset, limit=1000,
            )
            rows = list(response.body.get("data", []))

            for row in rows:
                if row.get("option_symbol"):
                    continue  # an option trade, not a stock - not tracked here

                symbol = row.get("symbol")
                if not symbol or not symbol.get("symbol"):
                    continue  # no ticker attached - not a trade we can match

                security_type = ((symbol.get("type") or {}).get("code") or "").lower()
                if security_type in _NON_STOCK_SECURITY_TYPES:
                    continue  # a money-market fund, bond, etc - not a stock trade

                trade_date = row.get("trade_date")
                if not trade_date:
                    continue
                if isinstance(trade_date, str):
                    trade_date = datetime.fromisoformat(trade_date.replace("Z", "+00:00"))
                # SnapTrade timestamps come back in UTC - converted to
                # Eastern (like everything else in this app, see
                # timeutil.py) before dropping the time-of-day, so a
                # trade late in the evening ET doesn't get filed under
                # the wrong calendar day.
                if trade_date.tzinfo is not None:
                    trade_date = trade_date.astimezone(timeutil.EASTERN).replace(tzinfo=None)

                transactions.append({
                    "date": trade_date,
                    "symbol": symbol["symbol"],
                    "action": row["type"],  # already "BUY" or "SELL", matching the CSV importers
                    "price": float(row["price"]),
                    "quantity": abs(float(row["units"])),
                })

            if len(rows) < 1000:
                break  # last page for this account
            offset += 1000

    return transactions
